/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.towerdefense.views;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author rolda
 */
public class Progreso extends javax.swing.JFrame {

    /**
     * Creates new form ds
     */
    public Progreso() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelOponente8 = new javax.swing.JLabel();
        labelOponente13 = new javax.swing.JLabel();
        labelOponente1 = new javax.swing.JLabel();
        labelOponente3 = new javax.swing.JLabel();
        labelOponente4 = new javax.swing.JLabel();
        labelOponente5 = new javax.swing.JLabel();
        labelOponente6 = new javax.swing.JLabel();
        labelOponente7 = new javax.swing.JLabel();
        labelOponente9 = new javax.swing.JLabel();
        labelOponente10 = new javax.swing.JLabel();
        labelOponente2 = new javax.swing.JLabel();
        labelOponente11 = new javax.swing.JLabel();
        labelOponente12 = new javax.swing.JLabel();
        labelOponente14 = new javax.swing.JLabel();
        labelOponente15 = new javax.swing.JLabel();
        labelOponente16 = new javax.swing.JLabel();
        labelOponente17 = new javax.swing.JLabel();
        labelEmperador = new javax.swing.JLabel();
        labelEmperador1 = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JButton();

        labelOponente8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        labelOponente13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelOponente1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente1.setOpaque(true);

        labelOponente3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente3.setOpaque(true);

        labelOponente4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente4.setOpaque(true);

        labelOponente5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelOponente5.setOpaque(true);

        labelOponente6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente6.setOpaque(true);

        labelOponente7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente7.setOpaque(true);

        labelOponente9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente9.setOpaque(true);

        labelOponente10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente10.setOpaque(true);

        labelOponente2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente2.setOpaque(true);

        labelOponente11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente11.setOpaque(true);

        labelOponente12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente12.setOpaque(true);

        labelOponente14.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente14.setOpaque(true);

        labelOponente15.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente15.setOpaque(true);

        labelOponente16.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente16.setOpaque(true);

        labelOponente17.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelOponente17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOponente17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelOponente17.setOpaque(true);

        labelEmperador.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelEmperador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmperador.setText("Emperador");
        labelEmperador.setOpaque(true);
        labelEmperador.setPreferredSize(new java.awt.Dimension(96, 24));

        labelEmperador1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        labelEmperador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmperador1.setText("Progreso de las batallas");
        labelEmperador1.setPreferredSize(new java.awt.Dimension(96, 24));

        btnEmpezar.setBackground(new java.awt.Color(0, 102, 204));
        btnEmpezar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmpezar.setText("Empezar");
        btnEmpezar.setOpaque(true);
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(labelOponente12, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelOponente5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOponente1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelOponente16, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOponente17, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(332, 332, 332))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(353, 353, 353)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelOponente2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelOponente11, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelOponente14, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelOponente15, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmperador, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelOponente9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOponente10, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOponente7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOponente6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOponente4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOponente3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(labelEmperador1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelEmperador, labelOponente1, labelOponente10, labelOponente11, labelOponente12, labelOponente14, labelOponente15, labelOponente16, labelOponente17, labelOponente2, labelOponente3, labelOponente4, labelOponente5, labelOponente6, labelOponente7, labelOponente9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelEmperador1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelOponente1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(labelOponente5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelOponente12, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(labelOponente15, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEmperador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(225, 225, 225))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(labelOponente3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(labelOponente4, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelOponente17, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                .addGap(37, 37, 37)
                                .addComponent(labelOponente2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                .addGap(30, 30, 30)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelOponente6, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelOponente7, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(labelOponente11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addGap(31, 31, 31)))
                                .addGap(41, 41, 41)
                                .addComponent(labelOponente9, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(labelOponente10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(labelOponente16, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEmpezar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelOponente14, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                                .addGap(30, 30, 30)))))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Arena().setVisible(true);
    }//GEN-LAST:event_btnEmpezarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Progreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Progreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Progreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Progreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Progreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JLabel labelEmperador;
    private javax.swing.JLabel labelEmperador1;
    private javax.swing.JLabel labelOponente1;
    private javax.swing.JLabel labelOponente10;
    private javax.swing.JLabel labelOponente11;
    private javax.swing.JLabel labelOponente12;
    private javax.swing.JLabel labelOponente13;
    private javax.swing.JLabel labelOponente14;
    private javax.swing.JLabel labelOponente15;
    private javax.swing.JLabel labelOponente16;
    private javax.swing.JLabel labelOponente17;
    private javax.swing.JLabel labelOponente2;
    private javax.swing.JLabel labelOponente3;
    private javax.swing.JLabel labelOponente4;
    private javax.swing.JLabel labelOponente5;
    private javax.swing.JLabel labelOponente6;
    private javax.swing.JLabel labelOponente7;
    private javax.swing.JLabel labelOponente8;
    private javax.swing.JLabel labelOponente9;
    // End of variables declaration//GEN-END:variables
}
